### ISSUE TITLE
Compilation errors when launching npm run serve.e2e

### ISSUE THREAD

**Issue by qiuzhong** [01org/zephyrjs-ide#179] opened 2017-07-31 07:19 UTC
**Issue description**
Typescript compilation errors when launching npm run serve.e2e

**Current behavior**
Failed to compile zephyrjs-ide/node_modules/protractor/built/browser.d.ts.

**Expected behavior**
No typescript compilation error.

**Steps to reproduce**
1. `git clone https://github.com/01org/zephyrjs-ide `
2. `cd zephyrjs-ide && npm install`
3. `npm run serve.e2e`
```
[15:21:00] Starting 'build.js.e2e'...
C:/Workspace/Work/week31/zephyrjs-ide/node_modules/protractor/built/browser.d.ts(15,18): error TS2430: Interface 'AbstractExtendedWebDriver' incorrectly extends interface 'ExtendedWebDriver'.
  Types of property 'controlFlow' are incompatible.
    Type '() => promise.ControlFlow' is not assignable to type '() => promise.ControlFlow'. Two different types with this name exist, but they are unrelated.
      Type 'promise.ControlFlow' is not assignable to type 'promise.ControlFlow'. Two different types with this name exist, but they are unrelated.
        Types of property 'execute' are incompatible.
          Type '<T>(fn: () => T | promise.Promise<T>, opt_description?: string) => promise.Promise<T>' is not assignable to type '<T>(fn: () => T | promise.Promise<T>, opt_description?: string) => promise.Promise<T>'. Two different types with this name exist, but they are unrelated.
            Types of parameters 'fn' and 'fn' are incompatible.
              Type 'T | promise.Promise<T>' is not assignable to type 'T | promise.Promise<T>'. Two different types with this name exist, but they are unrelated.
                Type 'Promise<T>' is not assignable to type 'T | Promise<T>'.
                  Type 'promise.Promise<T>' is not assignable to type 'promise.Promise<T>'. Two different types with this name exist, but they are unrelated.
                    Types of property 'then' are incompatible.
                      Type '<R>(opt_callback?: (value: T) => R | promise.IThenable<R>, opt_errback?: (error: any) => any) => ...' is not assignable to type '<R>(opt_callback?: (value: T) => R | promise.IThenable<R>, opt_errback?: (error: any) => any) => ...'. Two different types with this name exist, but they are unrelated.
                        Types of parameters 'opt_callback' and 'opt_callback' are incompatible.
                          Type 'R | promise.IThenable<R>' is not assignable to type 'R | promise.IThenable<R>'. Two different types with this name exist, but they are unrelated.
                            Type 'IThenable<R>' is not assignable to type 'R | IThenable<R>'.
                              Type 'promise.IThenable<R>' is not assignable to type 'promise.IThenable<R>'. Two different types with this name exist, but they are unrelated.
                                Types of property 'then' are incompatible.
                                  Type '<R>(opt_callback?: (value: R) => R | promise.IThenable<R>, opt_errback?: (error: any) => any) => ...' is not assignable to type '<R>(opt_callback?: (value: R) => R | promise.IThenable<R>, opt_errback?: (error: any) => any) => ...'. Two different types with this name exist, but they are unrelated.
                                    Type 'Promise<R | IThenable<R>>' is not assignable to type 'Promise<R>'.
                                      Types of property 'then' are incompatible.
                                        Type '<R>(opt_callback?: (value: R | IThenable<R>) => R | IThenable<R>, opt_errback?: (error: any) => a...' is not assignable to type '<R>(opt_callback?: (value: R) => R | IThenable<R>, opt_errback?: (error: any) => any) => Promise<R>'.
                                          Types of parameters 'opt_callback' and 'opt_callback' are incompatible.
                                            Types of parameters 'value' and 'value' are incompatible.
                                              Type 'R | IThenable<R>' is not assignable to type 'R'.
                                                Type 'IThenable<R>' is not assignable to type 'R'.
[15:21:00] TypeScript: 1 semantic error
[15:21:00] TypeScript: emit succeeded (with errors)
```
**'JS IDE for Zephyr OS' version:** `X.Y.Z / abcd1234`
`v0.19.0-alpha / 18c7815`

**Comment by xiaoyu3x** [comment] 2017-09-21 07:06
This issue is still  reproduced  with commit [c5b35be](https://github.com/01org/zephyrjs-ide/commit/c5b35be17d8cc63de91c5c2da4d28308617bf882)

**Comment by xiaoyu3x** [comment] 2017-09-25 07:36
This issue isn't reproduced with commit [9bdb7d7](https://github.com/01org/zephyrjs-ide/commit/9bdb7d728ff2fd82cf7bae6c54883dc4050855dd)

**Comment by xiaoyu3x** [comment] 2017-10-10 01:59
hi, @qiuzhong 
This issue isn't produced with commit [3ca5e23](https://github.com/01org/zephyrjs-ide/commit/3ca5e23effd1ef9dddcfa49a963c660fd225cf0a), please closed it.

**Comment by siovene** [comment] 2017-10-10 05:30
Can't reproduce it either, closing.

**Closed by siovene** 2017-10-10 05:30 UTC
Labels: minor, system
